/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Conect: typeof import('./src/components/conect.vue')['default']
    copy: typeof import('./src/components/PalestraNoite22 copy.vue')['default']
    DataGerais: typeof import('./src/components/dataGerais.vue')['default']
    Datas: typeof import('./src/components/datas.vue')['default']
    DatasFotos: typeof import('./src/components/datasFotos.vue')['default']
    DatasInf: typeof import('./src/components/datasInf.vue')['default']
    DatasOficina: typeof import('./src/components/datasOficina.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    FormAdd: typeof import('./src/components/formAdd.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homen: typeof import('./src/components/homen.vue')['default']
    Inscricao: typeof import('./src/components/inscricao.vue')['default']
    ListUsers: typeof import('./src/components/listUsers.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    MidiaSa: typeof import('./src/components/midiaSa.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NosPage: typeof import('./src/components/nosPage.vue')['default']
    PalestraCarp: typeof import('./src/components/palestraCarp.vue')['default']
    PalestraCarp23: typeof import('./src/components/palestraCarp23.vue')['default']
    PalestraNoite22: typeof import('./src/components/PalestraNoite22.vue')['default']
    PalestraNoite23: typeof import('./src/components/PalestraNoite23.vue')['default']
    Palestras: typeof import('./src/components/palestraCarp.vue')['default']
    Preloader: typeof import('./src/components/preloader.vue')['default']
    QuemSomos: typeof import('./src/components/quemSomos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalipMidia: typeof import('./src/components/salipMidia.vue')['default']
    Slide: typeof import('./src/components/slide.vue')['default']
  }
}
