/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Conect: typeof import('./src/components/conect.vue')['default']
    Datas: typeof import('./src/components/datas.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    FormAdd: typeof import('./src/components/formAdd.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Inscricao: typeof import('./src/components/inscricao.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/slide.vue')['default']
  }
}
