/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/addUser': RouteRecordInfo<'/addUser', '/addUser', Record<never, never>, Record<never, never>>,
    '/datasGeral': RouteRecordInfo<'/datasGeral', '/datasGeral', Record<never, never>, Record<never, never>>,
    '/homenageados': RouteRecordInfo<'/homenageados', '/homenageados', Record<never, never>, Record<never, never>>,
    '/listaUsuarios': RouteRecordInfo<'/listaUsuarios', '/listaUsuarios', Record<never, never>, Record<never, never>>,
    '/loginADM': RouteRecordInfo<'/loginADM', '/loginADM', Record<never, never>, Record<never, never>>,
    '/midiasalipi': RouteRecordInfo<'/midiasalipi', '/midiasalipi', Record<never, never>, Record<never, never>>,
    '/quemSomos': RouteRecordInfo<'/quemSomos', '/quemSomos', Record<never, never>, Record<never, never>>,
    '/usuarios': RouteRecordInfo<'/usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
